In [4]:
import pandas as pd
import numpy as np

In [5]:
from google.colab import files

uploaded = files.upload()

Saving RIT+Opportunity+Wise+Data+-+Sheet1.csv to RIT+Opportunity+Wise+Data+-+Sheet1 (1).csv

In [6]:
df = pd.read_csv("RIT+Opportunity+Wise+Data+-+Sheet1.csv")
df.head()

,Learner SignUp DateTime,Opportunity Id,Opportunity Name,Opportunity Category,Opportunity End Date,First Name,Date of Birth,Gender,Country,Institution Name,Current/Intended Major,Entry created at,Status Description,Status Code,Apply Date,Opportunity Start Date
0,06/14/2023 12:30:35,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Faria,01/12/2001,Female,Pakistan,Nwihs,Radiology,03/11/2024 12:01:41,Started,1080,06/14/2023 12:36:09,11/03/2022 18:30:39
1,05/01/2023 05:29:16,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Poojitha,08/16/2000,Female,India,SAINT LOUIS,Information Systems,03/11/2024 12:01:41,Started,1080,05/01/2023 06:08:21,11/03/2022 18:30:39
2,04/09/2023 20:35:08,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Emmanuel,01/27/2002,Male,United States,Illinois Institute of Technology,Computer Science,03/11/2024 12:01:41,Started,1080,05/11/2023 1085640:21:29,11/03/2022 18:30:39
3,08/29/2023 05:20:03,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Amrutha Varshini,11/01/1999,Female,United States,Saint Louis University,Information Systems,03/11/2024 12:01:41,Team Allocated,1070,10/09/2023 22:02:42,11/03/2022 18:30:39
4,01/06/2023 15:26:36,00000000-0GN2-A0AY-7XK8-C5FZPP,Career Essentials: Getting Started with Your P...,Course,06/29/2024 18:52:39,Vinay Varshith,04/19/2000,Male,United States,Saint Louis University,Computer Science,03/11/2024 12:01:41,Started,1080,01/06/2023 15:40:10,11/03/2022 18:30:39

In [7]:
df.shape

(8558, 16)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8558 entries, 0 to 8557
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Learner SignUp DateTime  8558 non-null   object
 1   Opportunity Id           8558 non-null   object
 2   Opportunity Name         8558 non-null   object
 3   Opportunity Category     8558 non-null   object
 4   Opportunity End Date     8558 non-null   object
 5   First Name               8558 non-null   object
 6   Date of Birth            8558 non-null   object
 7   Gender                   8558 non-null   object
 8   Country                  8558 non-null   object
 9   Institution Name         8553 non-null   object
 10  Current/Intended Major   8553 non-null   object
 11  Entry created at         8558 non-null   object
 12  Status Description       8558 non-null   object
 13  Status Code              8558 non-null   int64
 14  Apply Date               8558 non-null   object
 15  Opportunity Start Date   4764 non-null   object
dtypes: int64(1), object(15)
memory usage: 1.0+ MB

In [9]:
df.isnull().sum()

Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date          0
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              5
Current/Intended Major        5
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     3794
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.columns

Index(['Learner SignUp DateTime', 'Opportunity Id', 'Opportunity Name',
       'Opportunity Category', 'Opportunity End Date', 'First Name',
       'Date of Birth', 'Gender', 'Country', 'Institution Name',
       'Current/Intended Major', 'Entry created at', 'Status Description',
       'Status Code', 'Apply Date', 'Opportunity Start Date'],
      dtype='object')

In [13]:
df.columns = df.columns.str.strip()

In [14]:
df.columns

Index(['Learner SignUp DateTime', 'Opportunity Id', 'Opportunity Name',
       'Opportunity Category', 'Opportunity End Date', 'First Name',
       'Date of Birth', 'Gender', 'Country', 'Institution Name',
       'Current/Intended Major', 'Entry created at', 'Status Description',
       'Status Code', 'Apply Date', 'Opportunity Start Date'],
      dtype='object')

In [16]:

text_cols = df.select_dtypes(include='object').columns

text_cols

Index(['Learner SignUp DateTime', 'Opportunity Id', 'Opportunity Name',
       'Opportunity Category', 'Opportunity End Date', 'First Name',
       'Date of Birth', 'Gender', 'Country', 'Institution Name',
       'Current/Intended Major', 'Entry created at', 'Status Description',
       'Apply Date', 'Opportunity Start Date'],
      dtype='object')

In [17]:
for col in text_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(15))

--- Learner SignUp DateTime ---
Learner SignUp DateTime
01/31/2024 15:11:57    16
02/21/2024 14:37:12    16
01/05/2023 16:33:15    16
01/03/2024 17:13:01    16
02/02/2024 21:06:36    16
09/16/2023 05:56:22    15
12/29/2023 21:42:40    15
10/03/2023 01:43:17    15
04/25/2023 09:13:19    15
01/19/2024 19:38:32    14
07/09/2023 06:53:09    14
07/19/2023 11:36:23    14
01/05/2024 05:18:11    14
02/13/2024 10:59:01    14
04/22/2023 05:21:40    14
Name: count, dtype: int64

--- Opportunity Id ---
Opportunity Id
00000000-0GN2-A0AY-7XK8-C5FZPP    1423
00000000-0GWQ-AXC5-X45C-2MHJ28     980
00000000-0GHB-4N83-QX9K-JM48K2     836
00000000-0GRA-BD28-CXVV-EYEX21     784
00000000-0GNT-FT74-MZT8-93VC0G     559
00000000-10GG-17ZM-AP4T-WQVBGQ     551
00000000-101B-RJY9-TVWC-6XG9BH     483
00000000-10SA-ZXDA-E05A-N2CGAN     478
00000000-0GZY-NNHV-FJWW-PTA9VX     419
00000000-10WC-BS50-CYGD-X97ES4     389
00000000-10CD-3CAK-3FZK-9VXKRM     331
00000000-10S6-HVRK-ZDAM-90C0F8     262
00000000-10GQ-RJHT-3G4S-BKGBY1     237
00000000-100J-PM3A-0WJ8-5T68M5     192
00000000-106T-FSAJ-KDBX-40ZGNV     138
Name: count, dtype: int64

--- Opportunity Name ---
Opportunity Name
Career Essentials: Getting Started with Your Professional Journey    1423
Data Visualization                                                    980
Project Management                                                    836
Health Care Management                                                784
Digital Marketing                                                     559
Data Visualization Associate                                          551
Business Consulting                                                   483
Project Management Associate                                          478
Innovation & Entrepreneurship                                         419
CPR/AED Certification                                                 389
Digital Strategy Virtual Internship                                   331
Startup Mastery Workshop                                              262
Freelance Mastery workshop                                            237
Jump Start: Developing your Emotional Intelligence                    225
UrbanRenew Challenge                                                  138
Name: count, dtype: int64

--- Opportunity Category ---
Opportunity Category
Internship     5421
Course         2037
Event           545
Competition     425
Engagement      130
Name: count, dtype: int64

--- Opportunity End Date ---
Opportunity End Date
03/11/2024 18:00:00         4159
06/29/2024 18:52:39         1423
04/12/2024 1095120:00:00     784
04/11/2024 1094400:00:00     478
06/30/2024 16:18:50          389
02/17/2024 11:30:00          262
03/08/2024 11:30:00          237
12/24/2025 03:34:00          192
04/29/2024 18:29:00          138
12/05/2025 12:59:00          121
03/13/2024 18:29:00          116
04/19/2024 18:29:00          112
10/31/2023 14:45:36           55
04/23/2024 16:36:47           46
12/05/2025 11:06:00           33
Name: count, dtype: int64

--- First Name ---
First Name
Bhargavi          40
Pavan Kumar       36
Divya             34
Rohith            32
John              28
Abhishek          28
Vaishnavi         28
Muhammad          27
Sai               26
Murali Krishna    25
Vinay             24
Vishal            23
Rakesh            23
Sravani           22
Sindhuja          20
Name: count, dtype: int64

--- Date of Birth ---
Date of Birth
05/20/2001    29
09/17/2000    28
09/17/2002    28
11/15/2001    25
06/21/2000    24
10/06/1995    23
08/24/2001    23
12/24/2001    22
03/18/2000    21
09/24/2000    20
03/03/2000    20
05/06/1998    20
10/13/2000    20
06/08/1992    20
09/24/2001    19
Name: count, dtype: int64

--- Gender ---
Gender
Male                     5018
Female                   3522
Don't want to specify      15
Other                       3
Name: count, dtype: int64

--- Country ---
Country
United States     3976
India             2836
Nigeria            760
Ghana              275
Pakistan           219
Bangladesh          65
Egypt               50
Ethiopia            38
Kenya               38
Rwanda              28
Nepal               21
United Kingdom      18
Turkey              17
Philippines         13
Uganda              12
Name: count, dtype: int64

--- Institution Name ---
Institution Name
Saint Louis University              2631
saint louis university               818
Saint Louis university               246
Saint louis university               214
SAINT LOUIS UNIVERSITY               106
Illinois Institute of Technology     103
Saint louis University               102
Webster University                    46
St Louis University                   43
Saint Louis                           37
saint Louis university                30
saint Louis University                30
saint louis                           29
saint louis University                29
University of Ibadan                  26
Name: count, dtype: int64

--- Current/Intended Major ---
Current/Intended Major
Information Systems                         2158
Computer Science                            1052
Health Data Science                          371
Cyber Security                               326
Computer Information Systems                 250
Computer Science and Information Systems     211
Computer Science and Engineering             210
Data Analytics                               204
Public Health                                140
Computer Engineering                         115
Artificial Intelligence                      113
Business Analytics                           112
Other                                         98
Analytics                                     91
Business Administration                       84
Name: count, dtype: int64

--- Entry created at ---
Entry created at
03/11/2024 12:02:04    141
03/11/2024 12:02:17    126
03/11/2024 12:02:57    123
03/11/2024 12:02:12    121
03/11/2024 12:02:05    121
03/11/2024 12:01:58    119
03/11/2024 12:02:27    119
03/11/2024 12:03:02    118
03/11/2024 12:01:42    117
03/11/2024 12:02:48    116
03/11/2024 12:02:18    114
03/11/2024 12:03:09    113
03/11/2024 12:02:53    112
03/11/2024 12:01:44    110
03/11/2024 12:01:59    109
Name: count, dtype: int64

--- Status Description ---
Status Description
Rejected          3569
Team Allocated    3276
Started            767
Dropped Out        617
Waitlisted         109
Applied            105
Withdraw            86
Rewards Award       29
Name: count, dtype: int64

--- Apply Date ---
Apply Date
08/29/2023 05:30:24    3
01/17/2024 19:23:52    2
08/20/2023 04:53:48    2
02/21/2024 06:01:42    2
01/05/2024 04:38:47    2
08/17/2023 12:28:25    2
01/29/2024 03:48:41    2
02/23/2024 03:45:02    2
02/17/2024 22:16:59    2
11/15/2023 17:39:35    1
02/16/2024 02:43:16    1
11/15/2023 22:27:31    1
01/31/2024 04:46:49    1
01/28/2024 07:48:35    1
01/30/2024 24:26:33    1
Name: count, dtype: int64

--- Opportunity Start Date ---
Opportunity Start Date
NaN                         3794
11/03/2022 18:30:39         1361
01/08/2024 03:30:46          988
01/22/2024 24:00:00          499
03/20/2023 02:30:00          341
02/17/2024 14:00:00          262
03/08/2024 14:00:00          222
01/28/2024 23:30:00          186
03/05/2024 1089960:00:00     153
03/21/2024 18:30:00          136
08/21/2023 06:30:54          118
01/28/2024 18:30:00          113
02/15/2024 18:30:00          110
02/19/2024 24:00:00          106
04/04/2024 1089264:00:00      49
Name: count, dtype: int64

In [18]:
# Removing leading and trailing spaces from text values
for col in text_cols:
    df[col] = df[col].str.strip()

In [21]:
date_cols = [
    'Learner SignUp DateTime',
    'Opportunity End Date',
    'Date of Birth',
    'Entry created at',
    'Apply Date',
    'Opportunity Start Date'
]

for col in date_cols:
    print(f"\n--- {col} ---")
    print(df[col].dropna().head(10))

--- Learner SignUp DateTime ---
0    06/14/2023 12:30:35
1    05/01/2023 05:29:16
2    04/09/2023 20:35:08
3    08/29/2023 05:20:03
4    01/06/2023 15:26:36
5    03/02/2024 19:16:07
6    05/31/2023 07:11:04
7    07/22/2023 07:30:25
8    03/20/2023 16:36:30
9    05/11/2023 03:40:33
Name: Learner SignUp DateTime, dtype: object

--- Opportunity End Date ---
0    06/29/2024 18:52:39
1    06/29/2024 18:52:39
2    06/29/2024 18:52:39
3    06/29/2024 18:52:39
4    06/29/2024 18:52:39
5    06/29/2024 18:52:39
6    06/29/2024 18:52:39
7    06/29/2024 18:52:39
8    06/29/2024 18:52:39
9    06/29/2024 18:52:39
Name: Opportunity End Date, dtype: object

--- Date of Birth ---
0    01/12/2001
1    08/16/2000
2    01/27/2002
3    11/01/1999
4    04/19/2000
5    05/12/1996
6    09/09/2001
7    02/27/2006
8    12/22/2005
9    06/26/1998
Name: Date of Birth, dtype: object

--- Entry created at ---
0    03/11/2024 12:01:41
1    03/11/2024 12:01:41
2    03/11/2024 12:01:41
3    03/11/2024 12:01:41
4    03/11/2024 12:01:41
5    03/11/2024 12:01:41
6    03/11/2024 12:01:41
7    03/11/2024 12:01:41
8    03/11/2024 12:01:41
9    03/11/2024 12:01:41
Name: Entry created at, dtype: object

--- Apply Date ---
0         06/14/2023 12:36:09
1         05/01/2023 06:08:21
2    05/11/2023 1085640:21:29
3         10/09/2023 22:02:42
4         01/06/2023 15:40:10
5         03/02/2024 20:30:35
6         06/14/2023 05:29:41
7         07/22/2023 07:44:24
8         05/24/2023 13:44:09
9         12/17/2023 02:58:44
Name: Apply Date, dtype: object

--- Opportunity Start Date ---
0     11/03/2022 18:30:39
1     11/03/2022 18:30:39
2     11/03/2022 18:30:39
3     11/03/2022 18:30:39
4     11/03/2022 18:30:39
6     11/03/2022 18:30:39
7     11/03/2022 18:30:39
8     11/03/2022 18:30:39
9     11/03/2022 18:30:39
10    11/03/2022 18:30:39
Name: Opportunity Start Date, dtype: object

In [22]:
for col in date_cols:
    converted = pd.to_datetime(df[col], errors='coerce')

    invalid = df[col].notna() & converted.isna()

    print(f"\n--- {col} ---")
    print("Invalid values:", invalid.sum())

    if invalid.sum() > 0:
        print(df.loc[invalid, col].head(10))

--- Learner SignUp DateTime ---
Invalid values: 295
51          01/24/2024 24:25:19
93     06/10/2023 1084920:58:20
139    03/07/2024 1091424:10:44
155         08/19/2023 24:13:56
178         08/15/2023 24:37:14
255         01/24/2024 24:21:05
260    05/03/2023 1079760:49:54
268         04/15/2023 24:47:58
274    11/10/2023 1085040:47:35
296         03/18/2023 24:47:56
Name: Learner SignUp DateTime, dtype: object

--- Opportunity End Date ---
Invalid values: 1262
1986    04/12/2024 1095120:00:00
1987    04/12/2024 1095120:00:00
1988    04/12/2024 1095120:00:00
1989    04/12/2024 1095120:00:00
1990    04/12/2024 1095120:00:00
1991    04/12/2024 1095120:00:00
1992    04/12/2024 1095120:00:00
1993    04/12/2024 1095120:00:00
1994    04/12/2024 1095120:00:00
1995    04/12/2024 1095120:00:00
Name: Opportunity End Date, dtype: object

--- Date of Birth ---
Invalid values: 0

--- Entry created at ---
Invalid values: 0

--- Apply Date ---
Invalid values: 307
2      05/11/2023 1085640:21:29
51          01/24/2024 24:57:44
139    03/07/2024 1091424:19:25
143    02/10/2024 1093608:11:58
265    02/06/2024 1090680:04:21
284         08/31/2023 24:28:42
316         08/22/2023 24:15:06
346         01/28/2024 24:46:53
348         09/27/2023 24:45:14
373    08/11/2023 1085712:45:57
Name: Apply Date, dtype: object

--- Opportunity Start Date ---
Invalid values: 843
1428         01/22/2024 24:00:00
1434         02/19/2024 24:00:00
1465         01/22/2024 24:00:00
1472    03/05/2024 1089960:00:00
1474         01/22/2024 24:00:00
1478         03/18/2024 24:00:00
1479    03/05/2024 1089960:00:00
1480         01/22/2024 24:00:00
1482         01/22/2024 24:00:00
1487         03/18/2024 24:00:00
Name: Opportunity Start Date, dtype: object

In [23]:
for col in date_cols:
    converted = pd.to_datetime(df[col], errors='coerce')
    invalid = df[col].notna() & converted.isna()

    if invalid.sum() > 0:
        print(f"\n--- {col}: {invalid.sum()} invalid values ---")
        print(df.loc[invalid, col].value_counts().head(20))

--- Learner SignUp DateTime: 295 invalid values ---
Learner SignUp DateTime
02/13/2024 24:10:25         13
04/02/2024 1087824:17:42    11
02/24/2024 24:22:07         11
10/08/2023 1083552:39:50    11
11/10/2023 1085040:47:35    10
09/10/2023 1084992:35:18     8
12/22/2023 24:25:42          8
01/24/2024 24:25:48          8
01/29/2024 24:43:23          8
02/24/2024 24:53:19          8
08/23/2023 24:25:23          8
02/09/2024 1092888:36:40     8
07/05/2023 1081272:50:31     6
09/09/2023 1084272:56:48     6
12/25/2023 24:18:23          6
11/03/2023 1079904:55:23     6
02/16/2024 24:11:00          5
09/10/2023 1084992:47:04     5
08/31/2023 24:37:10          5
02/21/2024 24:51:29          5
Name: count, dtype: int64

--- Opportunity End Date: 1262 invalid values ---
Opportunity End Date
04/12/2024 1095120:00:00    784
04/11/2024 1094400:00:00    478
Name: count, dtype: int64

--- Apply Date: 307 invalid values ---
Apply Date
02/27/2024 24:49:24         1
05/11/2023 1085640:21:29    1
01/24/2024 24:57:44         1
02/17/2024 24:03:09         1
02/13/2024 24:31:29         1
01/24/2024 24:32:33         1
02/13/2024 24:18:53         1
02/23/2024 24:56:36         1
02/13/2024 24:27:32         1
01/30/2024 24:30:57         1
01/16/2024 24:02:30         1
02/07/2024 1091400:59:03    1
12/28/2023 24:26:45         1
02/27/2024 24:47:29         1
01/13/2024 24:49:10         1
01/20/2024 24:58:08         1
03/01/2024 1087056:13:47    1
04/01/2024 1087080:18:07    1
02/29/2024 24:14:37         1
07/20/2023 24:44:45         1
Name: count, dtype: int64

--- Opportunity Start Date: 843 invalid values ---
Opportunity Start Date
01/22/2024 24:00:00         499
03/05/2024 1089960:00:00    153
02/19/2024 24:00:00         106
04/04/2024 1089264:00:00     49
03/18/2024 24:00:00          36
Name: count, dtype: int64

In [24]:
# Create backup copies before modifying anything
for col in date_cols:
    df[col + '_original'] = df[col]

# Extract only the date portion and convert it safely
for col in date_cols:
    df[col] = pd.to_datetime(
        df[col].astype('string').str.split().str[0],
        format='%m/%d/%Y',
        errors='coerce'
    )

In [25]:
for col in date_cols:
    print(col, "-> Missing after cleaning:", df[col].isna().sum())

Learner SignUp DateTime -> Missing after cleaning: 0
Opportunity End Date -> Missing after cleaning: 0
Date of Birth -> Missing after cleaning: 0
Entry created at -> Missing after cleaning: 0
Apply Date -> Missing after cleaning: 4
Opportunity Start Date -> Missing after cleaning: 3794

In [26]:
df.loc[df['Apply Date'].isna(), ['Apply Date', 'Apply Date_original']]

     Apply Date       Apply Date_original
806         NaT  13/05/2023 1081416:14:20
1764        NaT  13/05/2023 1081416:23:34
5749        NaT  13/05/2023 1081416:27:04
6856        NaT  13/05/2023 1081416:31:38

In [27]:
mask = df['Apply Date'].isna() & df['Apply Date_original'].notna()

df.loc[mask, 'Apply Date'] = pd.to_datetime(
    df.loc[mask, 'Apply Date_original'].str.split().str[0],
    format='%d/%m/%Y',
    errors='coerce'
)

In [28]:
df['Apply Date'].isna().sum()

np.int64(0)

In [30]:
df[df['Institution Name'].isna()][
    ['Institution Name', 'Current/Intended Major']
]

     Institution Name Current/Intended Major
239               NaN        Cloud Computing
1746              NaN      Digital Marketing
3347              NaN        Cloud Computing
4994              NaN       Computer Science
6021              NaN        Cloud Computing

In [32]:
df['Institution Name'] = df['Institution Name'].fillna('Unknown')
df['Current/Intended Major'] = df['Current/Intended Major'].fillna('Unknown')

In [33]:
print("Institution Name:", df['Institution Name'].isna().sum())
print("Current/Intended Major:", df['Current/Intended Major'].isna().sum())

Institution Name: 0
Current/Intended Major: 0

In [34]:
categorical_cols = [
    'Gender',
    'Country',
    'Opportunity Category',
    'Status Description'
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Gender ---
Gender
Male                     5018
Female                   3522
Don't want to specify      15
Other                       3
Name: count, dtype: int64

--- Country ---
Country
United States             3976
India                     2836
Nigeria                    760
Ghana                      275
Pakistan                   219
                          ...
Ireland                      1
Libyan Arab Jamahiriya       1
Afghanistan                  1
Bhutan                       1
Spain                        1
Name: count, Length: 71, dtype: int64

--- Opportunity Category ---
Opportunity Category
Internship     5421
Course         2037
Event           545
Competition     425
Engagement      130
Name: count, dtype: int64

--- Status Description ---
Status Description
Rejected          3569
Team Allocated    3276
Started            767
Dropped Out        617
Waitlisted         109
Applied            105
Withdraw            86
Rewards Award       29
Name: count, dtype: int64

In [35]:
print("Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Dataset Shape: (8558, 22)

Missing Values:
Learner SignUp DateTime                0
Opportunity Id                         0
Opportunity Name                       0
Opportunity Category                   0
Opportunity End Date                   0
First Name                             0
Date of Birth                          0
Gender                                 0
Country                                0
Institution Name                       0
Current/Intended Major                 0
Entry created at                       0
Status Description                     0
Status Code                            0
Apply Date                             0
Opportunity Start Date              3794
Learner SignUp DateTime_original       0
Opportunity End Date_original          0
Date of Birth_original                 0
Entry created at_original              0
Apply Date_original                    0
Opportunity Start Date_original     3794
dtype: int64

Duplicate Rows: 0

Data Types:
Learner SignUp DateTime             datetime64[ns]
Opportunity Id                              object
Opportunity Name                            object
Opportunity Category                        object
Opportunity End Date                datetime64[ns]
First Name                                  object
Date of Birth                       datetime64[ns]
Gender                                      object
Country                                     object
Institution Name                            object
Current/Intended Major                      object
Entry created at                    datetime64[ns]
Status Description                          object
Status Code                                  int64
Apply Date                          datetime64[ns]
Opportunity Start Date              datetime64[ns]
Learner SignUp DateTime_original            object
Opportunity End Date_original               object
Date of Birth_original                      object
Entry created at_original                   object
Apply Date_original                         object
Opportunity Start Date_original             object
dtype: object

In [36]:
original_cols = [col for col in df.columns if col.endswith('_original')]
df.drop(columns=original_cols, inplace=True)

print("Final shape:", df.shape)

Final shape: (8558, 16)

In [37]:
df.to_csv("Cleaned_RIT_Opportunity_Data.csv", index=False)

In [38]:
print("Duplicates:", df.duplicated().sum())
print("\nMissing values:")
print(df.isnull().sum())

Duplicates: 2

Missing values:
Learner SignUp DateTime       0
Opportunity Id                0
Opportunity Name              0
Opportunity Category          0
Opportunity End Date          0
First Name                    0
Date of Birth                 0
Gender                        0
Country                       0
Institution Name              0
Current/Intended Major        0
Entry created at              0
Status Description            0
Status Code                   0
Apply Date                    0
Opportunity Start Date     3794
dtype: int64

In [39]:
from google.colab import files
files.download("Cleaned_RIT_Opportunity_Data.csv")